import { Career } from '@/types';

class CareersService {
  private readonly STORAGE_KEY_CAREERS = 'unimatch_careers';
  private readonly STORAGE_KEY_STUDENT_INTERESTS = 'unimatch_student_interests';

  // Helper function to add missing properties to career objects
  private addMissingProperties(career: any): Career {
    return {
      ...career,
      category: career.category || career.industry,
      average_salary: career.average_salary || {
        entry_level: career.average_salary_entry,
        mid_level: career.average_salary_mid,
        senior_level: career.average_salary_senior
      },
      growth_rate: career.growth_rate || 10,
      learn_more_url: career.learn_more_url || `https://www.careers.govt.nz/jobs-database/${career.industry.toLowerCase()}/${career.name.toLowerCase().replace(/\s+/g, '-')}/`,
      alternative_courses: career.alternative_courses || []
    };
  }

  // Comprehensive career data with multiple industries and careers
  private sampleCareers: any[] = [
    // HEALTHCARE INDUSTRY (12 careers)
    {
      career_id: 'CAREER001',
      name: 'Medical Doctor',
      description: 'Diagnose and treat patients, perform surgeries, and provide medical care. Requires extensive education and training.',
      category: 'Healthcare',
      required_courses: ['Medicine', 'Surgery', 'Anatomy', 'Physiology'],
      skills_required: ['Communication', 'Problem Solving', 'Empathy', 'Attention to Detail', 'Critical Thinking'],
      average_salary_entry: 450000,
      average_salary_mid: 800000,
      average_salary_senior: 1200000,
      average_salary: {
        entry_level: 450000,
        mid_level: 800000,
        senior_level: 1200000
      },
      job_market_outlook: 'High demand',
      growth_rate: 15,
      learn_more_url: 'https://www.careers.govt.nz/jobs-database/health/doctor/',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Medicine and Bachelor of Surgery (MBChB)',
      experience_requirements: '2 years internship + community service',
      work_environment: 'Hospitals, clinics, private practice',
      career_path: ['Medical Student', 'Intern', 'Medical Officer', 'Specialist', 'Consultant'],
      related_careers: ['Nurse', 'Pharmacist', 'Physiotherapist', 'Dentist'],
      industry: 'Healthcare',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER002',
      name: 'Registered Nurse',
      description: 'Provide direct patient care, assist doctors, and educate patients about health conditions.',
      category: 'Healthcare',
      required_courses: ['Nursing', 'Anatomy', 'Physiology', 'Patient Care'],
      skills_required: ['Compassion', 'Communication', 'Attention to Detail', 'Physical Stamina', 'Critical Thinking'],
      average_salary_entry: 280000,
      average_salary_mid: 420000,
      average_salary_senior: 650000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Nursing or Diploma in Nursing',
      experience_requirements: 'Clinical practice during studies',
      work_environment: 'Hospitals, clinics, home care, community health',
      career_path: ['Student Nurse', 'Staff Nurse', 'Senior Nurse', 'Nurse Manager', 'Chief Nursing Officer'],
      related_careers: ['Medical Doctor', 'Physiotherapist', 'Occupational Therapist', 'Midwife'],
      industry: 'Healthcare',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER003',
      name: 'Pharmacist',
      description: 'Dispense medications, provide drug information, and ensure safe medication use.',
      required_courses: ['Pharmacy', 'Chemistry', 'Pharmacology', 'Pharmaceutical Care'],
      skills_required: ['Attention to Detail', 'Communication', 'Analytical Thinking', 'Customer Service', 'Knowledge of Medications'],
      average_salary_entry: 350000,
      average_salary_mid: 550000,
      average_salary_senior: 800000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Pharmacy (BPharm)',
      experience_requirements: '1 year internship',
      work_environment: 'Pharmacies, hospitals, pharmaceutical companies',
      career_path: ['Intern Pharmacist', 'Pharmacist', 'Senior Pharmacist', 'Pharmacy Manager', 'Pharmaceutical Director'],
      related_careers: ['Medical Doctor', 'Nurse', 'Pharmaceutical Sales Rep', 'Clinical Research Associate'],
      industry: 'Healthcare',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER004',
      name: 'Physiotherapist',
      description: 'Help patients recover from injuries and improve physical function through exercise and therapy.',
      required_courses: ['Physiotherapy', 'Anatomy', 'Physiology', 'Exercise Science'],
      skills_required: ['Physical Fitness', 'Communication', 'Empathy', 'Problem Solving', 'Manual Dexterity'],
      average_salary_entry: 300000,
      average_salary_mid: 480000,
      average_salary_senior: 720000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Physiotherapy',
      experience_requirements: '1 year community service',
      work_environment: 'Hospitals, clinics, sports facilities, private practice',
      career_path: ['Student Physiotherapist', 'Physiotherapist', 'Senior Physiotherapist', 'Practice Manager', 'Clinical Director'],
      related_careers: ['Occupational Therapist', 'Sports Medicine Doctor', 'Massage Therapist', 'Rehabilitation Counselor'],
      industry: 'Healthcare',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER005',
      name: 'Dentist',
      description: 'Diagnose and treat dental problems, perform oral surgery, and promote oral health.',
      required_courses: ['Dentistry', 'Oral Biology', 'Dental Materials', 'Oral Surgery'],
      skills_required: ['Manual Dexterity', 'Attention to Detail', 'Communication', 'Problem Solving', 'Patience'],
      average_salary_entry: 400000,
      average_salary_mid: 700000,
      average_salary_senior: 1100000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Dental Surgery (BDS)',
      experience_requirements: '1 year internship',
      work_environment: 'Dental clinics, hospitals, private practice',
      career_path: ['Dental Student', 'Intern Dentist', 'General Dentist', 'Specialist Dentist', 'Practice Owner'],
      related_careers: ['Dental Hygienist', 'Dental Assistant', 'Oral Surgeon', 'Orthodontist'],
      industry: 'Healthcare',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER006',
      name: 'Psychologist',
      description: 'Study human behavior and mental processes, provide therapy and counseling services.',
      required_courses: ['Psychology', 'Research Methods', 'Statistics', 'Clinical Psychology'],
      skills_required: ['Empathy', 'Communication', 'Active Listening', 'Analytical Thinking', 'Patience'],
      average_salary_entry: 320000,
      average_salary_mid: 520000,
      average_salary_senior: 850000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Master of Psychology or PhD in Psychology',
      experience_requirements: '2 years supervised practice',
      work_environment: 'Private practice, hospitals, schools, corporate settings',
      career_path: ['Psychology Intern', 'Psychologist', 'Senior Psychologist', 'Clinical Director', 'Private Practice Owner'],
      related_careers: ['Psychiatrist', 'Social Worker', 'Counselor', 'Mental Health Nurse'],
      industry: 'Healthcare',
      work_life_balance: 'Good',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER007',
      name: 'Radiologist',
      description: 'Interpret medical images to diagnose diseases and conditions using X-rays, MRI, and CT scans.',
      required_courses: ['Medicine', 'Radiology', 'Anatomy', 'Pathology'],
      skills_required: ['Analytical Thinking', 'Attention to Detail', 'Technical Skills', 'Communication', 'Problem Solving'],
      average_salary_entry: 500000,
      average_salary_mid: 900000,
      average_salary_senior: 1400000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'MBChB + 4 years radiology specialization',
      experience_requirements: '2 years internship + 4 years specialization',
      work_environment: 'Hospitals, diagnostic centers, private practice',
      career_path: ['Medical Officer', 'Radiology Registrar', 'Radiologist', 'Senior Radiologist', 'Head of Radiology'],
      related_careers: ['Medical Doctor', 'Radiographer', 'Nuclear Medicine Technologist', 'Ultrasound Technician'],
      industry: 'Healthcare',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER008',
      name: 'Veterinarian',
      description: 'Diagnose and treat diseases and injuries in animals, perform surgeries, and provide preventive care.',
      required_courses: ['Veterinary Medicine', 'Animal Biology', 'Surgery', 'Pharmacology'],
      skills_required: ['Compassion for Animals', 'Manual Dexterity', 'Problem Solving', 'Communication', 'Physical Stamina'],
      average_salary_entry: 380000,
      average_salary_mid: 600000,
      average_salary_senior: 950000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Veterinary Science (BVSc)',
      experience_requirements: '1 year internship',
      work_environment: 'Veterinary clinics, animal hospitals, farms, zoos',
      career_path: ['Veterinary Intern', 'Veterinarian', 'Senior Veterinarian', 'Practice Owner', 'Specialist Veterinarian'],
      related_careers: ['Veterinary Technician', 'Animal Behaviorist', 'Wildlife Biologist', 'Animal Nutritionist'],
      industry: 'Healthcare',
      work_life_balance: 'Fair',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER009',
      name: 'Occupational Therapist',
      description: 'Help patients develop, recover, and improve skills needed for daily living and working.',
      required_courses: ['Occupational Therapy', 'Anatomy', 'Psychology', 'Rehabilitation'],
      skills_required: ['Empathy', 'Communication', 'Problem Solving', 'Creativity', 'Patience'],
      average_salary_entry: 290000,
      average_salary_mid: 460000,
      average_salary_senior: 700000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Occupational Therapy',
      experience_requirements: '1 year community service',
      work_environment: 'Hospitals, clinics, schools, rehabilitation centers',
      career_path: ['OT Student', 'Occupational Therapist', 'Senior OT', 'OT Manager', 'Clinical Director'],
      related_careers: ['Physiotherapist', 'Speech Therapist', 'Rehabilitation Counselor', 'Social Worker'],
      industry: 'Healthcare',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER010',
      name: 'Speech Therapist',
      description: 'Assess and treat communication and swallowing disorders in patients of all ages.',
      required_courses: ['Speech Therapy', 'Linguistics', 'Psychology', 'Anatomy'],
      skills_required: ['Communication', 'Patience', 'Empathy', 'Analytical Thinking', 'Creativity'],
      average_salary_entry: 270000,
      average_salary_mid: 440000,
      average_salary_senior: 680000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Speech Therapy',
      experience_requirements: '1 year community service',
      work_environment: 'Hospitals, clinics, schools, private practice',
      career_path: ['Speech Therapy Student', 'Speech Therapist', 'Senior Speech Therapist', 'Clinical Supervisor', 'Private Practice Owner'],
      related_careers: ['Occupational Therapist', 'Audiologist', 'Special Education Teacher', 'Psychologist'],
      industry: 'Healthcare',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER011',
      name: 'Midwife',
      description: 'Provide care and support to women during pregnancy, childbirth, and postpartum period.',
      required_courses: ['Midwifery', 'Anatomy', 'Physiology', 'Maternal Health'],
      skills_required: ['Compassion', 'Communication', 'Physical Stamina', 'Problem Solving', 'Emotional Support'],
      average_salary_entry: 260000,
      average_salary_mid: 420000,
      average_salary_senior: 650000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Midwifery or Diploma in Midwifery',
      experience_requirements: 'Clinical practice during studies',
      work_environment: 'Hospitals, clinics, home births, community health',
      career_path: ['Student Midwife', 'Midwife', 'Senior Midwife', 'Midwifery Manager', 'Clinical Director'],
      related_careers: ['Nurse', 'Obstetrician', 'Gynecologist', 'Lactation Consultant'],
      industry: 'Healthcare',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER012',
      name: 'Emergency Medical Technician',
      description: 'Provide emergency medical care and transport patients to medical facilities.',
      required_courses: ['Emergency Medical Care', 'Anatomy', 'Physiology', 'Trauma Care'],
      skills_required: ['Physical Stamina', 'Quick Decision Making', 'Communication', 'Stress Management', 'Teamwork'],
      average_salary_entry: 180000,
      average_salary_mid: 300000,
      average_salary_senior: 450000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Certificate in Emergency Medical Care',
      experience_requirements: 'On-the-job training',
      work_environment: 'Ambulances, hospitals, emergency services',
      career_path: ['EMT Student', 'EMT', 'Senior EMT', 'Paramedic', 'Emergency Services Manager'],
      related_careers: ['Nurse', 'Firefighter', 'Police Officer', 'Emergency Room Doctor'],
      industry: 'Healthcare',
      work_life_balance: 'Poor',
      job_security: 'High',
      advancement_opportunities: 'Fair'
    },

    // TECHNOLOGY INDUSTRY (15 careers)
    {
      career_id: 'CAREER013',
      name: 'Software Developer',
      description: 'Design, develop, and maintain software applications and systems using programming languages.',
      required_courses: ['Computer Science', 'Software Engineering', 'Programming', 'Data Structures'],
      skills_required: ['Programming', 'Problem Solving', 'Logical Thinking', 'Teamwork', 'Continuous Learning'],
      average_salary_entry: 350000,
      average_salary_mid: 650000,
      average_salary_senior: 1200000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Computer Science or Software Engineering',
      experience_requirements: 'Portfolio of projects',
      work_environment: 'Tech companies, startups, corporate IT departments',
      career_path: ['Junior Developer', 'Developer', 'Senior Developer', 'Tech Lead', 'Engineering Manager'],
      related_careers: ['Web Developer', 'Mobile App Developer', 'DevOps Engineer', 'Data Scientist'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER014',
      name: 'Data Scientist',
      description: 'Analyze complex data to help organizations make informed decisions using statistical methods and machine learning.',
      required_courses: ['Data Science', 'Statistics', 'Machine Learning', 'Python Programming'],
      skills_required: ['Analytical Thinking', 'Programming', 'Statistics', 'Machine Learning', 'Communication'],
      average_salary_entry: 450000,
      average_salary_mid: 800000,
      average_salary_senior: 1400000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor or Master in Data Science, Statistics, or Computer Science',
      experience_requirements: 'Portfolio of data projects',
      work_environment: 'Tech companies, consulting firms, research institutions',
      career_path: ['Junior Data Scientist', 'Data Scientist', 'Senior Data Scientist', 'Lead Data Scientist', 'Chief Data Officer'],
      related_careers: ['Data Analyst', 'Machine Learning Engineer', 'Business Intelligence Analyst', 'Research Scientist'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER015',
      name: 'Cybersecurity Analyst',
      description: 'Protect organizations from cyber threats by monitoring systems and implementing security measures.',
      required_courses: ['Cybersecurity', 'Computer Science', 'Network Security', 'Ethical Hacking'],
      skills_required: ['Analytical Thinking', 'Attention to Detail', 'Problem Solving', 'Technical Skills', 'Communication'],
      average_salary_entry: 400000,
      average_salary_mid: 750000,
      average_salary_senior: 1300000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Cybersecurity, Computer Science, or Information Technology',
      experience_requirements: 'Relevant certifications (CISSP, CEH)',
      work_environment: 'Corporations, government agencies, consulting firms',
      career_path: ['Security Analyst', 'Senior Security Analyst', 'Security Manager', 'Chief Information Security Officer'],
      related_careers: ['Network Administrator', 'IT Auditor', 'Penetration Tester', 'Security Consultant'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER016',
      name: 'UX/UI Designer',
      description: 'Design user interfaces and experiences for digital products to ensure they are intuitive and user-friendly.',
      required_courses: ['Design', 'User Experience', 'Human-Computer Interaction', 'Visual Design'],
      skills_required: ['Creativity', 'User Research', 'Design Tools', 'Communication', 'Problem Solving'],
      average_salary_entry: 320000,
      average_salary_mid: 580000,
      average_salary_senior: 950000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Design, Human-Computer Interaction, or related field',
      experience_requirements: 'Portfolio of design projects',
      work_environment: 'Tech companies, design agencies, startups',
      career_path: ['Junior Designer', 'UX/UI Designer', 'Senior Designer', 'Design Lead', 'Head of Design'],
      related_careers: ['Graphic Designer', 'Product Manager', 'Web Developer', 'User Researcher'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER017',
      name: 'DevOps Engineer',
      description: 'Bridge development and operations teams by automating deployment and infrastructure management.',
      required_courses: ['Computer Science', 'Cloud Computing', 'System Administration', 'Automation'],
      skills_required: ['Technical Skills', 'Automation', 'Problem Solving', 'Communication', 'Continuous Learning'],
      average_salary_entry: 420000,
      average_salary_mid: 780000,
      average_salary_senior: 1350000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Computer Science or Information Technology',
      experience_requirements: 'Experience with cloud platforms and automation tools',
      work_environment: 'Tech companies, cloud providers, enterprise IT',
      career_path: ['Junior DevOps', 'DevOps Engineer', 'Senior DevOps', 'DevOps Lead', 'Infrastructure Manager'],
      related_careers: ['Software Developer', 'System Administrator', 'Cloud Architect', 'Site Reliability Engineer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER018',
      name: 'Product Manager',
      description: 'Lead product development from conception to launch, working with cross-functional teams.',
      required_courses: ['Business', 'Product Management', 'Marketing', 'Technology'],
      skills_required: ['Leadership', 'Communication', 'Strategic Thinking', 'Analytical Skills', 'Technical Understanding'],
      average_salary_entry: 500000,
      average_salary_mid: 900000,
      average_salary_senior: 1500000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Business, Engineering, or related field',
      experience_requirements: '2-3 years in product or business roles',
      work_environment: 'Tech companies, startups, large corporations',
      career_path: ['Associate PM', 'Product Manager', 'Senior PM', 'Principal PM', 'VP of Product'],
      related_careers: ['Project Manager', 'Business Analyst', 'Marketing Manager', 'Software Developer'],
      industry: 'Technology',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER019',
      name: 'Cloud Architect',
      description: 'Design and implement cloud infrastructure solutions for organizations migrating to cloud platforms.',
      required_courses: ['Cloud Computing', 'Computer Science', 'System Architecture', 'Security'],
      skills_required: ['Technical Skills', 'Architecture Design', 'Problem Solving', 'Communication', 'Cloud Platforms'],
      average_salary_entry: 600000,
      average_salary_mid: 1100000,
      average_salary_senior: 1800000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Computer Science or Information Technology',
      experience_requirements: '5+ years in cloud technologies and architecture',
      work_environment: 'Cloud providers, consulting firms, enterprise IT',
      career_path: ['Cloud Engineer', 'Cloud Architect', 'Senior Cloud Architect', 'Principal Architect', 'CTO'],
      related_careers: ['DevOps Engineer', 'System Administrator', 'Solutions Architect', 'Infrastructure Engineer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER020',
      name: 'Mobile App Developer',
      description: 'Create mobile applications for iOS and Android platforms using various programming languages.',
      required_courses: ['Mobile Development', 'Programming', 'User Interface Design', 'Software Engineering'],
      skills_required: ['Programming', 'Mobile Platforms', 'UI/UX Understanding', 'Problem Solving', 'Creativity'],
      average_salary_entry: 380000,
      average_salary_mid: 680000,
      average_salary_senior: 1150000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Computer Science or Software Engineering',
      experience_requirements: 'Portfolio of mobile apps',
      work_environment: 'Tech companies, mobile app agencies, startups',
      career_path: ['Junior Mobile Developer', 'Mobile Developer', 'Senior Mobile Developer', 'Mobile Lead', 'Mobile Director'],
      related_careers: ['Software Developer', 'Web Developer', 'UX/UI Designer', 'Product Manager'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER021',
      name: 'AI/ML Engineer',
      description: 'Develop and implement artificial intelligence and machine learning solutions for various applications.',
      required_courses: ['Machine Learning', 'Artificial Intelligence', 'Computer Science', 'Mathematics'],
      skills_required: ['Programming', 'Machine Learning', 'Mathematics', 'Problem Solving', 'Research Skills'],
      average_salary_entry: 500000,
      average_salary_mid: 950000,
      average_salary_senior: 1600000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Master or PhD in AI, Machine Learning, or Computer Science',
      experience_requirements: 'Research experience and ML project portfolio',
      work_environment: 'Tech companies, research labs, AI startups',
      career_path: ['ML Engineer', 'Senior ML Engineer', 'Principal ML Engineer', 'AI Research Scientist', 'Chief AI Officer'],
      related_careers: ['Data Scientist', 'Research Scientist', 'Software Developer', 'Robotics Engineer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER022',
      name: 'Game Developer',
      description: 'Create video games for various platforms including consoles, PC, and mobile devices.',
      required_courses: ['Game Development', 'Programming', 'Game Design', 'Computer Graphics'],
      skills_required: ['Programming', 'Creativity', 'Game Design', 'Problem Solving', 'Teamwork'],
      average_salary_entry: 300000,
      average_salary_mid: 550000,
      average_salary_senior: 900000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Game Development, Computer Science, or related field',
      experience_requirements: 'Portfolio of game projects',
      work_environment: 'Game studios, indie development, tech companies',
      career_path: ['Junior Game Developer', 'Game Developer', 'Senior Game Developer', 'Lead Developer', 'Game Director'],
      related_careers: ['Software Developer', '3D Artist', 'Game Designer', 'Animator'],
      industry: 'Technology',
      work_life_balance: 'Fair',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER023',
      name: 'Blockchain Developer',
      description: 'Develop decentralized applications and smart contracts using blockchain technology.',
      required_courses: ['Blockchain Technology', 'Programming', 'Cryptography', 'Distributed Systems'],
      skills_required: ['Programming', 'Blockchain', 'Cryptography', 'Problem Solving', 'Innovation'],
      average_salary_entry: 450000,
      average_salary_mid: 850000,
      average_salary_senior: 1400000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Computer Science or related field',
      experience_requirements: 'Experience with blockchain platforms and smart contracts',
      work_environment: 'Crypto companies, fintech, blockchain startups',
      career_path: ['Blockchain Developer', 'Senior Blockchain Developer', 'Blockchain Architect', 'CTO'],
      related_careers: ['Software Developer', 'Cryptocurrency Analyst', 'Smart Contract Auditor', 'DeFi Developer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER024',
      name: 'IT Support Specialist',
      description: 'Provide technical support and troubleshooting for computer systems and software.',
      required_courses: ['Information Technology', 'Computer Systems', 'Networking', 'Customer Service'],
      skills_required: ['Technical Skills', 'Problem Solving', 'Communication', 'Patience', 'Customer Service'],
      average_salary_entry: 200000,
      average_salary_mid: 350000,
      average_salary_senior: 550000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Diploma or Bachelor in Information Technology',
      experience_requirements: 'Certifications (CompTIA A+, Network+)',
      work_environment: 'Corporate IT departments, help desks, managed service providers',
      career_path: ['Help Desk', 'IT Support', 'Senior IT Support', 'IT Manager', 'IT Director'],
      related_careers: ['System Administrator', 'Network Administrator', 'IT Consultant', 'Technical Writer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Fair'
    },
    {
      career_id: 'CAREER025',
      name: 'Database Administrator',
      description: 'Manage and maintain database systems to ensure data integrity and performance.',
      required_courses: ['Database Management', 'Computer Science', 'SQL', 'System Administration'],
      skills_required: ['Database Skills', 'Problem Solving', 'Attention to Detail', 'Technical Skills', 'Communication'],
      average_salary_entry: 350000,
      average_salary_mid: 600000,
      average_salary_senior: 950000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Computer Science or Information Technology',
      experience_requirements: 'Database certifications and experience',
      work_environment: 'Corporations, government agencies, database vendors',
      career_path: ['Junior DBA', 'Database Administrator', 'Senior DBA', 'Database Manager', 'Data Architect'],
      related_careers: ['Data Analyst', 'System Administrator', 'Data Engineer', 'Business Intelligence Analyst'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER026',
      name: 'Web Developer',
      description: 'Create and maintain websites and web applications using various programming languages and frameworks.',
      required_courses: ['Web Development', 'Programming', 'HTML/CSS', 'JavaScript'],
      skills_required: ['Programming', 'Web Technologies', 'Problem Solving', 'Creativity', 'Continuous Learning'],
      average_salary_entry: 280000,
      average_salary_mid: 520000,
      average_salary_senior: 850000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Computer Science or Web Development',
      experience_requirements: 'Portfolio of web projects',
      work_environment: 'Web agencies, tech companies, freelance',
      career_path: ['Junior Web Developer', 'Web Developer', 'Senior Web Developer', 'Lead Developer', 'Technical Director'],
      related_careers: ['Software Developer', 'UX/UI Designer', 'Frontend Developer', 'Backend Developer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER027',
      name: 'System Administrator',
      description: 'Manage and maintain computer systems, servers, and networks for organizations.',
      required_courses: ['System Administration', 'Networking', 'Operating Systems', 'Security'],
      skills_required: ['Technical Skills', 'Problem Solving', 'Attention to Detail', 'Communication', 'Troubleshooting'],
      average_salary_entry: 320000,
      average_salary_mid: 550000,
      average_salary_senior: 850000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Information Technology or Computer Science',
      experience_requirements: 'System administration certifications',
      work_environment: 'Corporations, government agencies, managed service providers',
      career_path: ['Junior SysAdmin', 'System Administrator', 'Senior SysAdmin', 'IT Manager', 'IT Director'],
      related_careers: ['Network Administrator', 'Database Administrator', 'IT Support Specialist', 'DevOps Engineer'],
      industry: 'Technology',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },

    // FINANCE INDUSTRY (12 careers)
    {
      career_id: 'CAREER028',
      name: 'Investment Banker',
      description: 'Help companies raise capital and provide financial advisory services for mergers and acquisitions.',
      required_courses: ['Finance', 'Economics', 'Accounting', 'Business'],
      skills_required: ['Analytical Skills', 'Communication', 'Financial Modeling', 'Attention to Detail', 'Stress Management'],
      average_salary_entry: 600000,
      average_salary_mid: 1200000,
      average_salary_senior: 2500000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Finance, Economics, or Business',
      experience_requirements: '2-3 years in finance or consulting',
      work_environment: 'Investment banks, financial institutions',
      career_path: ['Analyst', 'Associate', 'Vice President', 'Director', 'Managing Director'],
      related_careers: ['Financial Analyst', 'Corporate Finance Manager', 'Private Equity Associate', 'Hedge Fund Manager'],
      industry: 'Finance',
      work_life_balance: 'Poor',
      job_security: 'Medium',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER029',
      name: 'Financial Analyst',
      description: 'Analyze financial data to help businesses make investment and financial decisions.',
      required_courses: ['Finance', 'Accounting', 'Economics', 'Statistics'],
      skills_required: ['Analytical Skills', 'Excel', 'Financial Modeling', 'Communication', 'Attention to Detail'],
      average_salary_entry: 350000,
      average_salary_mid: 600000,
      average_salary_senior: 1000000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Finance, Accounting, or Economics',
      experience_requirements: 'CFA certification preferred',
      work_environment: 'Banks, investment firms, corporations',
      career_path: ['Junior Analyst', 'Financial Analyst', 'Senior Analyst', 'Finance Manager', 'CFO'],
      related_careers: ['Investment Banker', 'Portfolio Manager', 'Risk Manager', 'Credit Analyst'],
      industry: 'Finance',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER030',
      name: 'Accountant',
      description: 'Prepare and examine financial records, ensure accuracy, and help organizations comply with regulations.',
      required_courses: ['Accounting', 'Taxation', 'Auditing', 'Business Law'],
      skills_required: ['Attention to Detail', 'Mathematical Skills', 'Analytical Thinking', 'Communication', 'Integrity'],
      average_salary_entry: 250000,
      average_salary_mid: 450000,
      average_salary_senior: 750000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Accounting',
      experience_requirements: 'CA(SA) or CPA certification',
      work_environment: 'Accounting firms, corporations, government agencies',
      career_path: ['Junior Accountant', 'Accountant', 'Senior Accountant', 'Accounting Manager', 'CFO'],
      related_careers: ['Auditor', 'Tax Consultant', 'Financial Analyst', 'Bookkeeper'],
      industry: 'Finance',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER031',
      name: 'Insurance Underwriter',
      description: 'Evaluate insurance applications and determine coverage terms and pricing based on risk assessment.',
      required_courses: ['Insurance', 'Risk Management', 'Mathematics', 'Business'],
      skills_required: ['Analytical Skills', 'Risk Assessment', 'Attention to Detail', 'Communication', 'Decision Making'],
      average_salary_entry: 300000,
      average_salary_mid: 500000,
      average_salary_senior: 800000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Fair',
      education_requirements: 'Bachelor in Business, Finance, or related field',
      experience_requirements: 'Insurance industry experience',
      work_environment: 'Insurance companies, brokerage firms',
      career_path: ['Junior Underwriter', 'Underwriter', 'Senior Underwriter', 'Underwriting Manager', 'Chief Underwriter'],
      related_careers: ['Insurance Agent', 'Risk Manager', 'Actuary', 'Claims Adjuster'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Fair'
    },
    {
      career_id: 'CAREER032',
      name: 'Portfolio Manager',
      description: 'Manage investment portfolios for individuals and institutions to maximize returns while minimizing risk.',
      required_courses: ['Finance', 'Investment Management', 'Economics', 'Statistics'],
      skills_required: ['Analytical Skills', 'Risk Management', 'Communication', 'Decision Making', 'Market Knowledge'],
      average_salary_entry: 500000,
      average_salary_mid: 900000,
      average_salary_senior: 1500000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Finance or Economics, CFA preferred',
      experience_requirements: '5+ years in investment management',
      work_environment: 'Asset management firms, banks, investment companies',
      career_path: ['Research Analyst', 'Portfolio Manager', 'Senior Portfolio Manager', 'Chief Investment Officer'],
      related_careers: ['Financial Analyst', 'Investment Banker', 'Risk Manager', 'Wealth Manager'],
      industry: 'Finance',
      work_life_balance: 'Fair',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER033',
      name: 'Actuary',
      description: 'Analyze financial risks using mathematics, statistics, and financial theory to help businesses make decisions.',
      required_courses: ['Actuarial Science', 'Mathematics', 'Statistics', 'Finance'],
      skills_required: ['Mathematical Skills', 'Analytical Thinking', 'Problem Solving', 'Communication', 'Programming'],
      average_salary_entry: 400000,
      average_salary_mid: 700000,
      average_salary_senior: 1200000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Actuarial Science, Mathematics, or Statistics',
      experience_requirements: 'Actuarial exams and certifications',
      work_environment: 'Insurance companies, consulting firms, government agencies',
      career_path: ['Actuarial Analyst', 'Actuary', 'Senior Actuary', 'Chief Actuary', 'Actuarial Director'],
      related_careers: ['Risk Manager', 'Insurance Underwriter', 'Data Scientist', 'Financial Analyst'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER034',
      name: 'Credit Analyst',
      description: 'Evaluate creditworthiness of individuals and businesses applying for loans or credit.',
      required_courses: ['Finance', 'Accounting', 'Risk Management', 'Economics'],
      skills_required: ['Analytical Skills', 'Attention to Detail', 'Risk Assessment', 'Communication', 'Decision Making'],
      average_salary_entry: 280000,
      average_salary_mid: 480000,
      average_salary_senior: 750000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Finance, Accounting, or Economics',
      experience_requirements: 'Banking or finance experience',
      work_environment: 'Banks, credit unions, financial institutions',
      career_path: ['Junior Credit Analyst', 'Credit Analyst', 'Senior Credit Analyst', 'Credit Manager', 'Chief Risk Officer'],
      related_careers: ['Loan Officer', 'Risk Manager', 'Financial Analyst', 'Underwriter'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER035',
      name: 'Tax Consultant',
      description: 'Help individuals and businesses with tax planning, preparation, and compliance with tax regulations.',
      required_courses: ['Taxation', 'Accounting', 'Business Law', 'Finance'],
      skills_required: ['Tax Knowledge', 'Attention to Detail', 'Communication', 'Analytical Skills', 'Problem Solving'],
      average_salary_entry: 300000,
      average_salary_mid: 550000,
      average_salary_senior: 900000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Accounting or Taxation',
      experience_requirements: 'Tax certifications and experience',
      work_environment: 'Accounting firms, tax consulting firms, corporations',
      career_path: ['Junior Tax Consultant', 'Tax Consultant', 'Senior Tax Consultant', 'Tax Manager', 'Tax Director'],
      related_careers: ['Accountant', 'Financial Advisor', 'Tax Attorney', 'Bookkeeper'],
      industry: 'Finance',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER036',
      name: 'Wealth Manager',
      description: 'Provide comprehensive financial planning and investment management services to high-net-worth individuals.',
      required_courses: ['Finance', 'Investment Management', 'Estate Planning', 'Taxation'],
      skills_required: ['Communication', 'Financial Planning', 'Investment Knowledge', 'Client Relations', 'Analytical Skills'],
      average_salary_entry: 400000,
      average_salary_mid: 750000,
      average_salary_senior: 1300000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Finance or Business, CFP preferred',
      experience_requirements: '5+ years in financial services',
      work_environment: 'Private banks, wealth management firms, financial advisory firms',
      career_path: ['Junior Wealth Manager', 'Wealth Manager', 'Senior Wealth Manager', 'Managing Director', 'Partner'],
      related_careers: ['Financial Advisor', 'Portfolio Manager', 'Estate Planner', 'Investment Banker'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER037',
      name: 'Risk Manager',
      description: 'Identify, assess, and mitigate financial risks that could impact an organization.',
      required_courses: ['Risk Management', 'Finance', 'Statistics', 'Business'],
      skills_required: ['Risk Assessment', 'Analytical Skills', 'Communication', 'Problem Solving', 'Attention to Detail'],
      average_salary_entry: 450000,
      average_salary_mid: 800000,
      average_salary_senior: 1300000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor in Finance, Risk Management, or related field',
      experience_requirements: 'Risk management certifications and experience',
      work_environment: 'Banks, insurance companies, corporations, consulting firms',
      career_path: ['Risk Analyst', 'Risk Manager', 'Senior Risk Manager', 'Chief Risk Officer'],
      related_careers: ['Actuary', 'Insurance Underwriter', 'Compliance Officer', 'Financial Analyst'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER038',
      name: 'Compliance Officer',
      description: 'Ensure organizations comply with laws, regulations, and internal policies.',
      required_courses: ['Law', 'Compliance', 'Business', 'Ethics'],
      skills_required: ['Attention to Detail', 'Communication', 'Analytical Skills', 'Problem Solving', 'Integrity'],
      average_salary_entry: 350000,
      average_salary_mid: 600000,
      average_salary_senior: 950000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Law, Business, or related field',
      experience_requirements: 'Compliance experience and certifications',
      work_environment: 'Banks, financial institutions, corporations, government agencies',
      career_path: ['Compliance Analyst', 'Compliance Officer', 'Senior Compliance Officer', 'Chief Compliance Officer'],
      related_careers: ['Risk Manager', 'Legal Counsel', 'Auditor', 'Regulatory Affairs Manager'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER039',
      name: 'Financial Planner',
      description: 'Help individuals and families create comprehensive financial plans for their future goals.',
      required_courses: ['Financial Planning', 'Finance', 'Taxation', 'Investment Management'],
      skills_required: ['Communication', 'Financial Planning', 'Client Relations', 'Analytical Skills', 'Problem Solving'],
      average_salary_entry: 300000,
      average_salary_mid: 550000,
      average_salary_senior: 900000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Finance or Business, CFP certification',
      experience_requirements: 'Financial planning experience and certifications',
      work_environment: 'Financial advisory firms, banks, independent practices',
      career_path: ['Junior Financial Planner', 'Financial Planner', 'Senior Financial Planner', 'Practice Manager', 'Partner'],
      related_careers: ['Wealth Manager', 'Investment Advisor', 'Insurance Agent', 'Tax Consultant'],
      industry: 'Finance',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },

    // EDUCATION INDUSTRY (10 careers)
    {
      career_id: 'CAREER040',
      name: 'Teacher',
      description: 'Educate students in various subjects and grade levels, developing lesson plans and assessing student progress.',
      required_courses: ['Education', 'Subject Specialization', 'Child Development', 'Teaching Methods'],
      skills_required: ['Communication', 'Patience', 'Creativity', 'Classroom Management', 'Subject Knowledge'],
      average_salary_entry: 200000,
      average_salary_mid: 350000,
      average_salary_senior: 550000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Education (BEd) or Postgraduate Certificate in Education (PGCE)',
      experience_requirements: 'Teaching practice during studies',
      work_environment: 'Schools, colleges, universities, private tutoring',
      career_path: ['Student Teacher', 'Teacher', 'Senior Teacher', 'Head of Department', 'Principal'],
      related_careers: ['Educational Psychologist', 'Curriculum Developer', 'School Counselor', 'Education Administrator'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER041',
      name: 'University Professor',
      description: 'Teach at university level, conduct research, and publish academic papers in specialized fields.',
      required_courses: ['Doctorate in Specialized Field', 'Research Methods', 'Academic Writing', 'Teaching'],
      skills_required: ['Research Skills', 'Communication', 'Critical Thinking', 'Subject Expertise', 'Mentoring'],
      average_salary_entry: 400000,
      average_salary_mid: 700000,
      average_salary_senior: 1200000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Fair',
      education_requirements: 'PhD in specialized field',
      experience_requirements: 'Research publications and teaching experience',
      work_environment: 'Universities, research institutions, colleges',
      career_path: ['Lecturer', 'Senior Lecturer', 'Associate Professor', 'Professor', 'Department Head'],
      related_careers: ['Researcher', 'Academic Writer', 'Consultant', 'Policy Analyst'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER042',
      name: 'Educational Psychologist',
      description: 'Assess and support students with learning difficulties and behavioral challenges in educational settings.',
      required_courses: ['Psychology', 'Education', 'Child Development', 'Assessment Methods'],
      skills_required: ['Empathy', 'Analytical Skills', 'Communication', 'Problem Solving', 'Assessment Skills'],
      average_salary_entry: 350000,
      average_salary_mid: 600000,
      average_salary_senior: 950000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Master in Educational Psychology',
      experience_requirements: 'Supervised practice and registration',
      work_environment: 'Schools, clinics, private practice, government agencies',
      career_path: ['Trainee Psychologist', 'Educational Psychologist', 'Senior Psychologist', 'Lead Psychologist', 'Director'],
      related_careers: ['School Counselor', 'Clinical Psychologist', 'Special Education Teacher', 'Learning Support Specialist'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER043',
      name: 'Curriculum Developer',
      description: 'Design and develop educational curricula and learning materials for schools and training programs.',
      required_courses: ['Education', 'Curriculum Design', 'Subject Specialization', 'Assessment'],
      skills_required: ['Curriculum Design', 'Research Skills', 'Communication', 'Creativity', 'Project Management'],
      average_salary_entry: 300000,
      average_salary_mid: 500000,
      average_salary_senior: 800000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Education or related field',
      experience_requirements: 'Teaching experience and curriculum development',
      work_environment: 'Educational publishers, schools, government agencies, training companies',
      career_path: ['Curriculum Assistant', 'Curriculum Developer', 'Senior Developer', 'Curriculum Manager', 'Director'],
      related_careers: ['Teacher', 'Educational Consultant', 'Instructional Designer', 'Training Specialist'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER044',
      name: 'School Counselor',
      description: 'Provide academic, career, and personal counseling to students in educational institutions.',
      required_courses: ['Counseling', 'Psychology', 'Education', 'Career Development'],
      skills_required: ['Empathy', 'Communication', 'Active Listening', 'Problem Solving', 'Confidentiality'],
      average_salary_entry: 250000,
      average_salary_mid: 420000,
      average_salary_senior: 650000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Master in Counseling or School Psychology',
      experience_requirements: 'Counseling practicum and certification',
      work_environment: 'Schools, colleges, universities, private practice',
      career_path: ['Counseling Intern', 'School Counselor', 'Senior Counselor', 'Counseling Coordinator', 'Director'],
      related_careers: ['Educational Psychologist', 'Social Worker', 'Career Counselor', 'Mental Health Counselor'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER045',
      name: 'Training Specialist',
      description: 'Develop and deliver training programs for employees in corporate and organizational settings.',
      required_courses: ['Training and Development', 'Adult Learning', 'Instructional Design', 'Communication'],
      skills_required: ['Communication', 'Presentation Skills', 'Instructional Design', 'Adult Learning', 'Project Management'],
      average_salary_entry: 280000,
      average_salary_mid: 480000,
      average_salary_senior: 750000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Training, Education, or related field',
      experience_requirements: 'Training experience and certifications',
      work_environment: 'Corporations, training companies, government agencies, consulting firms',
      career_path: ['Training Assistant', 'Training Specialist', 'Senior Specialist', 'Training Manager', 'Director'],
      related_careers: ['Curriculum Developer', 'Human Resources Specialist', 'Instructional Designer', 'Learning and Development Manager'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER046',
      name: 'Librarian',
      description: 'Manage library resources, help users find information, and organize educational materials.',
      required_courses: ['Library Science', 'Information Management', 'Research Methods', 'Technology'],
      skills_required: ['Information Management', 'Research Skills', 'Communication', 'Technology Skills', 'Organization'],
      average_salary_entry: 220000,
      average_salary_mid: 380000,
      average_salary_senior: 600000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Fair',
      education_requirements: 'Master in Library Science (MLIS)',
      experience_requirements: 'Library experience and certifications',
      work_environment: 'Libraries, schools, universities, government agencies, corporations',
      career_path: ['Library Assistant', 'Librarian', 'Senior Librarian', 'Library Manager', 'Director'],
      related_careers: ['Archivist', 'Information Specialist', 'Research Assistant', 'Digital Asset Manager'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Fair'
    },
    {
      career_id: 'CAREER047',
      name: 'Education Administrator',
      description: 'Manage educational institutions, oversee operations, and implement educational policies.',
      required_courses: ['Education Administration', 'Management', 'Policy', 'Leadership'],
      skills_required: ['Leadership', 'Management', 'Communication', 'Strategic Planning', 'Problem Solving'],
      average_salary_entry: 400000,
      average_salary_mid: 700000,
      average_salary_senior: 1100000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Master in Education Administration or MBA',
      experience_requirements: 'Teaching and administrative experience',
      work_environment: 'Schools, universities, government agencies, educational organizations',
      career_path: ['Assistant Administrator', 'Education Administrator', 'Senior Administrator', 'Director', 'Superintendent'],
      related_careers: ['Principal', 'School Board Member', 'Policy Analyst', 'Education Consultant'],
      industry: 'Education',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER048',
      name: 'Special Education Teacher',
      description: 'Work with students who have special needs, adapting teaching methods and materials.',
      required_courses: ['Special Education', 'Education', 'Psychology', 'Adaptive Teaching'],
      skills_required: ['Patience', 'Adaptability', 'Communication', 'Empathy', 'Specialized Teaching Methods'],
      average_salary_entry: 250000,
      average_salary_mid: 420000,
      average_salary_senior: 650000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor in Special Education or Education with specialization',
      experience_requirements: 'Teaching practice with special needs students',
      work_environment: 'Special needs schools, mainstream schools, therapy centers',
      career_path: ['Student Teacher', 'Special Education Teacher', 'Senior Teacher', 'Department Head', 'Principal'],
      related_careers: ['Educational Psychologist', 'Occupational Therapist', 'Speech Therapist', 'School Counselor'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER049',
      name: 'Academic Researcher',
      description: 'Conduct research in academic institutions, publish findings, and contribute to knowledge in specialized fields.',
      required_courses: ['Research Methods', 'Statistics', 'Academic Writing', 'Specialized Field'],
      skills_required: ['Research Skills', 'Analytical Thinking', 'Writing', 'Critical Thinking', 'Persistence'],
      average_salary_entry: 300000,
      average_salary_mid: 550000,
      average_salary_senior: 900000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Fair',
      education_requirements: 'PhD in specialized field',
      experience_requirements: 'Research publications and grant writing',
      work_environment: 'Universities, research institutions, think tanks, government agencies',
      career_path: ['Research Assistant', 'Postdoc', 'Research Fellow', 'Senior Researcher', 'Research Director'],
      related_careers: ['University Professor', 'Policy Analyst', 'Consultant', 'Data Scientist'],
      industry: 'Education',
      work_life_balance: 'Good',
      job_security: 'Medium',
      advancement_opportunities: 'Fair'
    },

    // ENGINEERING INDUSTRY (12 careers)
    {
      career_id: 'CAREER050',
      name: 'Civil Engineer',
      description: 'Design and oversee construction of infrastructure projects like roads, bridges, and buildings.',
      required_courses: ['Civil Engineering', 'Mathematics', 'Physics', 'Structural Design'],
      skills_required: ['Problem Solving', 'Mathematical Skills', 'Project Management', 'Technical Drawing', 'Communication'],
      average_salary_entry: 350000,
      average_salary_mid: 650000,
      average_salary_senior: 1100000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Civil)',
      experience_requirements: 'Professional Engineer (PE) registration',
      work_environment: 'Construction companies, consulting firms, government agencies',
      career_path: ['Junior Engineer', 'Civil Engineer', 'Senior Engineer', 'Project Manager', 'Engineering Director'],
      related_careers: ['Structural Engineer', 'Environmental Engineer', 'Construction Manager', 'Urban Planner'],
      industry: 'Engineering',
      work_life_balance: 'Fair',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER051',
      name: 'Software Engineer',
      description: 'Design, develop, and maintain software systems and applications using engineering principles.',
      required_courses: ['Software Engineering', 'Computer Science', 'Programming', 'System Design'],
      skills_required: ['Programming', 'Problem Solving', 'System Design', 'Teamwork', 'Continuous Learning'],
      average_salary_entry: 400000,
      average_salary_mid: 750000,
      average_salary_senior: 1300000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Engineering (Software) or Computer Science',
      experience_requirements: 'Portfolio of software projects',
      work_environment: 'Tech companies, startups, corporate IT, consulting firms',
      career_path: ['Junior Engineer', 'Software Engineer', 'Senior Engineer', 'Lead Engineer', 'Engineering Manager'],
      related_careers: ['Software Developer', 'DevOps Engineer', 'System Architect', 'Product Manager'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER052',
      name: 'Mechanical Engineer',
      description: 'Design and develop mechanical systems, machines, and manufacturing processes.',
      required_courses: ['Mechanical Engineering', 'Mathematics', 'Physics', 'Thermodynamics'],
      skills_required: ['Problem Solving', 'Mathematical Skills', 'CAD Design', 'Project Management', 'Technical Skills'],
      average_salary_entry: 320000,
      average_salary_mid: 600000,
      average_salary_senior: 1000000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Mechanical)',
      experience_requirements: 'Professional Engineer (PE) registration',
      work_environment: 'Manufacturing companies, consulting firms, automotive industry',
      career_path: ['Junior Engineer', 'Mechanical Engineer', 'Senior Engineer', 'Project Manager', 'Engineering Director'],
      related_careers: ['Aerospace Engineer', 'Automotive Engineer', 'Manufacturing Engineer', 'Design Engineer'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER053',
      name: 'Electrical Engineer',
      description: 'Design and develop electrical systems, power generation, and electronic devices.',
      required_courses: ['Electrical Engineering', 'Mathematics', 'Physics', 'Circuit Design'],
      skills_required: ['Problem Solving', 'Mathematical Skills', 'Circuit Design', 'Technical Skills', 'Attention to Detail'],
      average_salary_entry: 340000,
      average_salary_mid: 620000,
      average_salary_senior: 1050000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Electrical)',
      experience_requirements: 'Professional Engineer (PE) registration',
      work_environment: 'Power companies, electronics firms, consulting firms, government agencies',
      career_path: ['Junior Engineer', 'Electrical Engineer', 'Senior Engineer', 'Project Manager', 'Engineering Director'],
      related_careers: ['Electronics Engineer', 'Power Systems Engineer', 'Control Systems Engineer', 'Telecommunications Engineer'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER054',
      name: 'Environmental Engineer',
      description: 'Develop solutions to environmental problems and ensure compliance with environmental regulations.',
      required_courses: ['Environmental Engineering', 'Chemistry', 'Biology', 'Environmental Science'],
      skills_required: ['Problem Solving', 'Environmental Knowledge', 'Project Management', 'Communication', 'Technical Skills'],
      average_salary_entry: 300000,
      average_salary_mid: 550000,
      average_salary_senior: 900000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Engineering (Environmental)',
      experience_requirements: 'Environmental certifications and experience',
      work_environment: 'Environmental consulting firms, government agencies, manufacturing companies',
      career_path: ['Junior Engineer', 'Environmental Engineer', 'Senior Engineer', 'Project Manager', 'Environmental Director'],
      related_careers: ['Civil Engineer', 'Environmental Scientist', 'Sustainability Consultant', 'Waste Management Specialist'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER055',
      name: 'Aerospace Engineer',
      description: 'Design and develop aircraft, spacecraft, and related systems and components.',
      required_courses: ['Aerospace Engineering', 'Mathematics', 'Physics', 'Aerodynamics'],
      skills_required: ['Problem Solving', 'Mathematical Skills', 'Technical Skills', 'Attention to Detail', 'Innovation'],
      average_salary_entry: 450000,
      average_salary_mid: 800000,
      average_salary_senior: 1300000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Aerospace)',
      experience_requirements: 'Aerospace industry experience',
      work_environment: 'Aerospace companies, defense contractors, government agencies, research institutions',
      career_path: ['Junior Engineer', 'Aerospace Engineer', 'Senior Engineer', 'Project Manager', 'Engineering Director'],
      related_careers: ['Mechanical Engineer', 'Aviation Engineer', 'Defense Engineer', 'Research Engineer'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER056',
      name: 'Chemical Engineer',
      description: 'Design and optimize chemical processes for manufacturing and production industries.',
      required_courses: ['Chemical Engineering', 'Chemistry', 'Mathematics', 'Process Design'],
      skills_required: ['Problem Solving', 'Mathematical Skills', 'Chemistry Knowledge', 'Process Design', 'Safety Awareness'],
      average_salary_entry: 360000,
      average_salary_mid: 650000,
      average_salary_senior: 1100000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Chemical)',
      experience_requirements: 'Chemical industry experience',
      work_environment: 'Chemical companies, pharmaceutical firms, oil and gas, consulting firms',
      career_path: ['Junior Engineer', 'Chemical Engineer', 'Senior Engineer', 'Process Manager', 'Engineering Director'],
      related_careers: ['Process Engineer', 'Petroleum Engineer', 'Materials Engineer', 'Environmental Engineer'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER057',
      name: 'Biomedical Engineer',
      description: 'Design and develop medical devices, prosthetics, and healthcare technology solutions.',
      required_courses: ['Biomedical Engineering', 'Biology', 'Medicine', 'Engineering Design'],
      skills_required: ['Problem Solving', 'Medical Knowledge', 'Technical Skills', 'Innovation', 'Attention to Detail'],
      average_salary_entry: 380000,
      average_salary_mid: 700000,
      average_salary_senior: 1200000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Excellent',
      education_requirements: 'Bachelor of Engineering (Biomedical)',
      experience_requirements: 'Medical device industry experience',
      work_environment: 'Medical device companies, hospitals, research institutions, consulting firms',
      career_path: ['Junior Engineer', 'Biomedical Engineer', 'Senior Engineer', 'Project Manager', 'Engineering Director'],
      related_careers: ['Medical Device Designer', 'Clinical Engineer', 'Rehabilitation Engineer', 'Healthcare Technology Specialist'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Excellent'
    },
    {
      career_id: 'CAREER058',
      name: 'Industrial Engineer',
      description: 'Optimize production processes and improve efficiency in manufacturing and service industries.',
      required_courses: ['Industrial Engineering', 'Operations Research', 'Statistics', 'Management'],
      skills_required: ['Problem Solving', 'Analytical Skills', 'Process Optimization', 'Communication', 'Project Management'],
      average_salary_entry: 320000,
      average_salary_mid: 580000,
      average_salary_senior: 950000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Industrial)',
      experience_requirements: 'Manufacturing or operations experience',
      work_environment: 'Manufacturing companies, consulting firms, logistics companies, government agencies',
      career_path: ['Junior Engineer', 'Industrial Engineer', 'Senior Engineer', 'Operations Manager', 'Director'],
      related_careers: ['Operations Manager', 'Supply Chain Manager', 'Quality Engineer', 'Process Improvement Specialist'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER059',
      name: 'Petroleum Engineer',
      description: 'Design and develop methods for extracting oil and gas from underground deposits.',
      required_courses: ['Petroleum Engineering', 'Geology', 'Mathematics', 'Reservoir Engineering'],
      skills_required: ['Problem Solving', 'Technical Skills', 'Geological Knowledge', 'Project Management', 'Safety Awareness'],
      average_salary_entry: 500000,
      average_salary_mid: 900000,
      average_salary_senior: 1500000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Fair',
      education_requirements: 'Bachelor of Engineering (Petroleum)',
      experience_requirements: 'Oil and gas industry experience',
      work_environment: 'Oil and gas companies, consulting firms, government agencies',
      career_path: ['Junior Engineer', 'Petroleum Engineer', 'Senior Engineer', 'Project Manager', 'Engineering Director'],
      related_careers: ['Geological Engineer', 'Drilling Engineer', 'Reservoir Engineer', 'Environmental Engineer'],
      industry: 'Engineering',
      work_life_balance: 'Fair',
      job_security: 'Medium',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER060',
      name: 'Telecommunications Engineer',
      description: 'Design and maintain telecommunications systems including networks, satellites, and wireless communications.',
      required_courses: ['Telecommunications Engineering', 'Electronics', 'Networking', 'Signal Processing'],
      skills_required: ['Technical Skills', 'Networking Knowledge', 'Problem Solving', 'Communication', 'Innovation'],
      average_salary_entry: 350000,
      average_salary_mid: 650000,
      average_salary_senior: 1100000,
      job_market_outlook: 'High demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Telecommunications)',
      experience_requirements: 'Telecommunications industry experience',
      work_environment: 'Telecom companies, consulting firms, government agencies, equipment manufacturers',
      career_path: ['Junior Engineer', 'Telecommunications Engineer', 'Senior Engineer', 'Network Manager', 'Engineering Director'],
      related_careers: ['Network Engineer', 'RF Engineer', 'Satellite Engineer', 'Wireless Engineer'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    },
    {
      career_id: 'CAREER061',
      name: 'Materials Engineer',
      description: 'Develop and test materials for various applications in manufacturing and construction.',
      required_courses: ['Materials Engineering', 'Chemistry', 'Physics', 'Materials Science'],
      skills_required: ['Problem Solving', 'Chemistry Knowledge', 'Testing Skills', 'Analytical Skills', 'Innovation'],
      average_salary_entry: 330000,
      average_salary_mid: 600000,
      average_salary_senior: 1000000,
      job_market_outlook: 'Moderate demand',
      growth_prospects: 'Good',
      education_requirements: 'Bachelor of Engineering (Materials)',
      experience_requirements: 'Materials testing and development experience',
      work_environment: 'Manufacturing companies, research institutions, consulting firms, aerospace industry',
      career_path: ['Junior Engineer', 'Materials Engineer', 'Senior Engineer', 'Research Manager', 'Engineering Director'],
      related_careers: ['Chemical Engineer', 'Metallurgist', 'Quality Engineer', 'Research Scientist'],
      industry: 'Engineering',
      work_life_balance: 'Good',
      job_security: 'High',
      advancement_opportunities: 'Good'
    }
  ];

  // Initialize careers data
  private initializeCareers(): void {
    const stored = localStorage.getItem(this.STORAGE_KEY_CAREERS);
    if (!stored) {
      const careersWithMissingProps = this.sampleCareers.map(career => this.addMissingProperties(career));
      localStorage.setItem(this.STORAGE_KEY_CAREERS, JSON.stringify(careersWithMissingProps));
    }
  }

  // Get all careers
  getAllCareers(): Career[] {
    this.initializeCareers();
    const stored = localStorage.getItem(this.STORAGE_KEY_CAREERS);
    return stored ? JSON.parse(stored) : this.sampleCareers;
  }

  // Get careers by industry
  getCareersByIndustry(industry: string): Career[] {
    return this.getAllCareers().filter(career => career.industry === industry);
  }

  // Get all industries
  getIndustries(): string[] {
    const careers = this.getAllCareers();
    const industries = [...new Set(careers.map(career => career.industry))];
    return industries.sort();
  }

  // Search careers by name or description
  searchCareers(query: string): Career[] {
    const careers = this.getAllCareers();
    const lowercaseQuery = query.toLowerCase();
    
    return careers.filter(career => 
      career.name.toLowerCase().includes(lowercaseQuery) ||
      career.description.toLowerCase().includes(lowercaseQuery) ||
      career.skills_required.some(skill => skill.toLowerCase().includes(lowercaseQuery))
    );
  }

  // Get career by ID
  getCareerById(careerId: string): Career | undefined {
    return this.getAllCareers().find(career => career.career_id === careerId);
  }

  // Get careers by demand level
  getCareersByDemand(demand: 'High demand' | 'Moderate demand' | 'Low demand'): Career[] {
    return this.getAllCareers().filter(career => career.job_market_outlook === demand);
  }

  // Get careers by growth prospects
  getCareersByGrowth(growth: 'Excellent' | 'Good' | 'Fair' | 'Poor'): Career[] {
    return this.getAllCareers().filter(career => career.growth_prospects === growth);
  }

  // Get careers by salary range
  getCareersBySalaryRange(minSalary: number, maxSalary: number): Career[] {
    return this.getAllCareers().filter(career => 
      career.average_salary_entry >= minSalary && career.average_salary_entry <= maxSalary
    );
  }

  // Get recommended careers based on student interests
  getRecommendedCareers(interests: string[]): Career[] {
    const careers = this.getAllCareers();
    
    return careers
      .map(career => {
        const score = interests.reduce((total, interest) => {
          const interestLower = interest.toLowerCase();
          let careerScore = 0;
          
          // Check if interest matches career name or description
          if (career.name.toLowerCase().includes(interestLower) ||
              career.description.toLowerCase().includes(interestLower)) {
            careerScore += 3;
          }
          
          // Check if interest matches skills
          if (career.skills_required.some(skill => 
              skill.toLowerCase().includes(interestLower))) {
            careerScore += 2;
          }
          
          // Check if interest matches industry
          if (career.industry.toLowerCase().includes(interestLower)) {
            careerScore += 1;
          }
          
          return total + careerScore;
        }, 0);
        
        return { career, score };
      })
      .filter(item => item.score > 0)
      .sort((a, b) => b.score - a.score)
      .map(item => item.career);
  }

  // Save student interests
  saveStudentInterests(studentId: string, interests: string[]): void {
    const key = `${this.STORAGE_KEY_STUDENT_INTERESTS}_${studentId}`;
    localStorage.setItem(key, JSON.stringify(interests));
  }

  // Get student interests
  getStudentInterests(studentId: string): string[] {
    const key = `${this.STORAGE_KEY_STUDENT_INTERESTS}_${studentId}`;
    const stored = localStorage.getItem(key);
    return stored ? JSON.parse(stored) : [];
  }

  // Get career statistics
  getCareerStatistics(): {
    totalCareers: number;
    industriesCount: number;
    averageSalary: number;
    highDemandCount: number;
    excellentGrowthCount: number;
  } {
    const careers = this.getAllCareers();
    const industries = this.getIndustries();
    
    const totalSalary = careers.reduce((sum, career) => sum + career.average_salary_entry, 0);
    const highDemandCareers = careers.filter(career => career.job_market_outlook === 'High demand');
    const excellentGrowthCareers = careers.filter(career => career.growth_prospects === 'Excellent');
    
    return {
      totalCareers: careers.length,
      industriesCount: industries.length,
      averageSalary: Math.round(totalSalary / careers.length),
      highDemandCount: highDemandCareers.length,
      excellentGrowthCount: excellentGrowthCareers.length
    };
  }
}

// Export singleton instance
export const careersService = new CareersService();
export default careersService;
   